// Autogenerated with StateSmith 0.11.2-alpha+4a4e30018e9a371124530fa96cf2ba3322b80459.
// Algorithm: Balanced1. See https://github.com/StateSmith/StateSmith/wiki/Algorithms

#pragma once
#include <stdint.h>

typedef enum StatusLedSm_EventId
{
    StatusLedSm_EventId_DO = 0, // The `do` event is special. State event handlers do not consume this event (ancestors all get it too) unless a transition occurs.
} StatusLedSm_EventId;

enum
{
    StatusLedSm_EventIdCount = 1
};

typedef enum StatusLedSm_StateId
{
    StatusLedSm_StateId_ROOT = 0,
    StatusLedSm_StateId_BOOT1 = 1,
    StatusLedSm_StateId_BOOT2 = 2,
    StatusLedSm_StateId_ERROR_SEQ1 = 3,
    StatusLedSm_StateId_ERROR_SEQ2 = 4,
    StatusLedSm_StateId_ERROR_SEQ3 = 5,
    StatusLedSm_StateId_RUNNING_GROUP = 6,
    StatusLedSm_StateId_RUNNING_OK = 7,
    StatusLedSm_StateId_RUNNING_OK_SEQ2 = 8,
    StatusLedSm_StateId_WARNING = 9,
    StatusLedSm_StateId_WARNING_SEQ2 = 10,
} StatusLedSm_StateId;

enum
{
    StatusLedSm_StateIdCount = 11
};


// Generated state machine
// forward declaration
typedef struct StatusLedSm StatusLedSm;

// event handler type
typedef void (*StatusLedSm_Func)(StatusLedSm* sm);

// State machine constructor. Must be called before start or dispatch event functions. Not thread safe.
void StatusLedSm_ctor(StatusLedSm* sm);

// Starts the state machine. Must be called before dispatching events. Not thread safe.
void StatusLedSm_start(StatusLedSm* sm);

// Dispatches an event to the state machine. Not thread safe.
void StatusLedSm_dispatch_event(StatusLedSm* sm, StatusLedSm_EventId event_id);

// Thread safe.
char const * StatusLedSm_state_id_to_string(StatusLedSm_StateId id);

// Thread safe.
char const * StatusLedSm_event_id_to_string(StatusLedSm_EventId id);

// Generated state machine
struct StatusLedSm
{
    // Used internally by state machine. Feel free to inspect, but don't modify.
    StatusLedSm_StateId state_id;
    
    // Used internally by state machine. Don't modify.
    StatusLedSm_Func ancestor_event_handler;
    
    // Used internally by state machine. Don't modify.
    StatusLedSm_Func current_event_handlers[StatusLedSm_EventIdCount];
    
    // Used internally by state machine. Don't modify.
    StatusLedSm_Func current_state_exit_handler;
};

