// Autogenerated with StateSmith 0.10.0-alpha+5d891f5c87fb9c6bf8f44217a56a71a3988f2734.
// Algorithm: Balanced1. See https://github.com/StateSmith/StateSmith/wiki/Algorithms

// License: MIT
// Copyright blah blah blah

#pragma once
#include <stdint.h>

typedef enum LightSm_EventId
{
    LightSm_EventId_DIM = 0,
    LightSm_EventId_INC = 1,
    LightSm_EventId_TOGGLE = 2,
} LightSm_EventId;

enum
{
    LightSm_EventIdCount = 3
};

typedef enum LightSm_StateId
{
    LightSm_StateId_ROOT = 0,
    LightSm_StateId_OFF = 1,
    LightSm_StateId_ON_GROUP = 2,
    LightSm_StateId_ON1 = 3,
    LightSm_StateId_ON2 = 4,
    LightSm_StateId_ON3 = 5,
} LightSm_StateId;

enum
{
    LightSm_StateIdCount = 6
};

typedef enum LightSm_ON_GROUP_HistoryId
{
    LightSm_ON_GROUP_HistoryId_ON1 = 0, // default transition
    LightSm_ON_GROUP_HistoryId_ON2 = 1,
    LightSm_ON_GROUP_HistoryId_ON3 = 2,
} LightSm_ON_GROUP_HistoryId;


// Generated state machine
// forward declaration
typedef struct LightSm LightSm;

// State machine variables. Can be used for inputs, outputs, user variables...
typedef struct LightSm_Vars
{
    LightSm_ON_GROUP_HistoryId ON_GROUP_history;
} LightSm_Vars;



// event handler type
typedef void (*LightSm_Func)(LightSm* sm);

// State machine constructor. Must be called before start or dispatch event functions. Not thread safe.
void LightSm_ctor(LightSm* sm);

// Starts the state machine. Must be called before dispatching events. Not thread safe.
void LightSm_start(LightSm* sm);

// Dispatches an event to the state machine. Not thread safe.
void LightSm_dispatch_event(LightSm* sm, LightSm_EventId event_id);

// Thread safe.
char const * LightSm_state_id_to_string(LightSm_StateId id);

// Thread safe.
char const * LightSm_event_id_to_string(LightSm_EventId id);

// Generated state machine
struct LightSm
{
    // Used internally by state machine. Feel free to inspect, but don't modify.
    LightSm_StateId state_id;
    
    // Used internally by state machine. Don't modify.
    LightSm_Func ancestor_event_handler;
    
    // Used internally by state machine. Don't modify.
    LightSm_Func current_event_handlers[LightSm_EventIdCount];
    
    // Used internally by state machine. Don't modify.
    LightSm_Func current_state_exit_handler;
    
    // Variables. Can be used for inputs, outputs, user variables...
    LightSm_Vars vars;
};

