// Autogenerated with StateSmith 0.11.2-alpha+4a4e30018e9a371124530fa96cf2ba3322b80459.
// Algorithm: Balanced1. See https://github.com/StateSmith/StateSmith/wiki/Algorithms

#pragma once
#include <stdint.h>

typedef enum SolarUiSm_EventId
{
    SolarUiSm_EventId_DOWN = 0,
    SolarUiSm_EventId_LEFT = 1,
    SolarUiSm_EventId_RIGHT = 2,
    SolarUiSm_EventId_UP = 3,
} SolarUiSm_EventId;

enum
{
    SolarUiSm_EventIdCount = 4
};

typedef enum SolarUiSm_StateId
{
    SolarUiSm_StateId_ROOT = 0,
    SolarUiSm_StateId_BATTERY_STATS = 1,
    SolarUiSm_StateId_BATTERY_STATS_1 = 2,
    SolarUiSm_StateId_BATTERY_STATS_2 = 3,
    SolarUiSm_StateId_BATTERY_STATS_3 = 4,
    SolarUiSm_StateId_HOME = 5,
    SolarUiSm_StateId_MAIN_MENU = 6,
    SolarUiSm_StateId_MAIN_MENU_1 = 7,
    SolarUiSm_StateId_MAIN_MENU_2 = 8,
    SolarUiSm_StateId_SOLAR_STATS = 9,
    SolarUiSm_StateId_SOLAR_STATS_1 = 10,
    SolarUiSm_StateId_SOLAR_STATS_2 = 11,
    SolarUiSm_StateId_SOLAR_STATS_3 = 12,
    SolarUiSm_StateId_SPLASH = 13,
} SolarUiSm_StateId;

enum
{
    SolarUiSm_StateIdCount = 14
};


// Generated state machine
// forward declaration
typedef struct SolarUiSm SolarUiSm;

// event handler type
typedef void (*SolarUiSm_Func)(SolarUiSm* sm);

// State machine constructor. Must be called before start or dispatch event functions. Not thread safe.
void SolarUiSm_ctor(SolarUiSm* sm);

// Starts the state machine. Must be called before dispatching events. Not thread safe.
void SolarUiSm_start(SolarUiSm* sm);

// Dispatches an event to the state machine. Not thread safe.
void SolarUiSm_dispatch_event(SolarUiSm* sm, SolarUiSm_EventId event_id);

// Thread safe.
char const * SolarUiSm_state_id_to_string(SolarUiSm_StateId id);

// Thread safe.
char const * SolarUiSm_event_id_to_string(SolarUiSm_EventId id);

// Generated state machine
struct SolarUiSm
{
    // Used internally by state machine. Feel free to inspect, but don't modify.
    SolarUiSm_StateId state_id;
    
    // Used internally by state machine. Don't modify.
    SolarUiSm_Func ancestor_event_handler;
    
    // Used internally by state machine. Don't modify.
    SolarUiSm_Func current_event_handlers[SolarUiSm_EventIdCount];
    
    // Used internally by state machine. Don't modify.
    SolarUiSm_Func current_state_exit_handler;
};

