// Autogenerated with StateSmith 0.9.8.
// Algorithm: Balanced1. See https://github.com/StateSmith/StateSmith/wiki/Algorithms

#include "MySm.h"
#include <stdbool.h> // required for `consume_event` flag
#include <string.h> // for memset

// This function is used when StateSmith doesn't know what the active leaf state is at
// compile time due to sub states or when multiple states need to be exited.
static void exit_up_to_state_handler(MySm* sm, MySm_Func desired_state_exit_handler);

static void ROOT_enter(MySm* sm);

static void ROOT_exit(MySm* sm);

static void ROOT_do(MySm* sm);

static void ROOT_press(MySm* sm);

static void ERROR_enter(MySm* sm);

static void ERROR_exit(MySm* sm);

static void ERROR_press(MySm* sm);

static void NORMAL_enter(MySm* sm);

static void NORMAL_exit(MySm* sm);

static void NORMAL_do(MySm* sm);

static void RUNNING_enter(MySm* sm);

static void RUNNING_exit(MySm* sm);

static void PRE_HEAT_enter(MySm* sm);

static void PRE_HEAT_exit(MySm* sm);

static void PRE_HEAT_do(MySm* sm);

static void WARM_ENOUGH_enter(MySm* sm);

static void WARM_ENOUGH_exit(MySm* sm);

static void STARTUP_BEEP_enter(MySm* sm);

static void STARTUP_BEEP_exit(MySm* sm);

static void STARTUP_BEEP_do(MySm* sm);


// State machine constructor. Must be called before start or dispatch event functions. Not thread safe.
void MySm_ctor(MySm* sm)
{
    memset(sm, 0, sizeof(*sm));
}

// Starts the state machine. Must be called before dispatching events. Not thread safe.
void MySm_start(MySm* sm)
{
    ROOT_enter(sm);
    // ROOT behavior
    // uml: TransitionTo(ROOT.<InitialState>)
    {
        // Step 1: Exit states until we reach `ROOT` state (Least Common Ancestor for transition). Already at LCA, no exiting required.
        
        // Step 2: Transition action: ``.
        
        // Step 3: Enter/move towards transition target `ROOT.<InitialState>`.
        // ROOT.<InitialState> is a pseudo state and cannot have an `enter` trigger.
        
        // ROOT.<InitialState> behavior
        // uml: TransitionTo(STARTUP_BEEP)
        {
            // Step 1: Exit states until we reach `ROOT` state (Least Common Ancestor for transition). Already at LCA, no exiting required.
            
            // Step 2: Transition action: ``.
            
            // Step 3: Enter/move towards transition target `STARTUP_BEEP`.
            NORMAL_enter(sm);
            STARTUP_BEEP_enter(sm);
            
            // Step 4: complete transition. Ends event dispatch. No other behaviors are checked.
            sm->state_id = MySm_StateId_STARTUP_BEEP;
            // No ancestor handles event. Can skip nulling `ancestor_event_handler`.
            return;
        } // end of behavior for ROOT.<InitialState>
    } // end of behavior for ROOT
}

// Dispatches an event to the state machine. Not thread safe.
void MySm_dispatch_event(MySm* sm, MySm_EventId event_id)
{
    MySm_Func behavior_func = sm->current_event_handlers[event_id];
    
    while (behavior_func != NULL)
    {
        sm->ancestor_event_handler = NULL;
        behavior_func(sm);
        behavior_func = sm->ancestor_event_handler;
    }
}

// This function is used when StateSmith doesn't know what the active leaf state is at
// compile time due to sub states or when multiple states need to be exited.
static void exit_up_to_state_handler(MySm* sm, MySm_Func desired_state_exit_handler)
{
    while (sm->current_state_exit_handler != desired_state_exit_handler)
    {
        sm->current_state_exit_handler(sm);
    }
}


////////////////////////////////////////////////////////////////////////////////
// event handlers for state ROOT
////////////////////////////////////////////////////////////////////////////////

static void ROOT_enter(MySm* sm)
{
    // setup trigger/event handlers
    sm->current_state_exit_handler = ROOT_exit;
    sm->current_event_handlers[MySm_EventId_DO] = ROOT_do;
    sm->current_event_handlers[MySm_EventId_PRESS] = ROOT_press;
}

static void ROOT_exit(MySm* sm)
{
    // State machine root is a special case. It cannot be exited. Mark as unused.
    (void)sm;
}

static void ROOT_do(MySm* sm)
{
    // No ancestor state handles `do` event.
    
    // ROOT behavior
    // uml: (do, PRESS) / { log_unhandled_event(); }
    {
        // Step 1: execute action `log_unhandled_event();`
        log_unhandled_event();
        
        // Step 2: determine if ancestor gets to handle event next.
        // Don't consume special `do` event.
    } // end of behavior for ROOT
}

static void ROOT_press(MySm* sm)
{
    // No ancestor state handles `press` event.
    
    // ROOT behavior
    // uml: (do, PRESS) / { log_unhandled_event(); }
    {
        // Step 1: execute action `log_unhandled_event();`
        log_unhandled_event();
        
        // Step 2: determine if ancestor gets to handle event next.
        // No ancestor handles event. Can skip nulling `ancestor_event_handler`.
    } // end of behavior for ROOT
}


////////////////////////////////////////////////////////////////////////////////
// event handlers for state ERROR
////////////////////////////////////////////////////////////////////////////////

static void ERROR_enter(MySm* sm)
{
    // setup trigger/event handlers
    sm->current_state_exit_handler = ERROR_exit;
    sm->current_event_handlers[MySm_EventId_PRESS] = ERROR_press;
    
    // ERROR behavior
    // uml: enter / { shut_stuff_off(); }
    {
        // Step 1: execute action `shut_stuff_off();`
        shut_stuff_off();
    } // end of behavior for ERROR
}

static void ERROR_exit(MySm* sm)
{
    // adjust function pointers for this state's exit
    sm->current_state_exit_handler = ROOT_exit;
    sm->current_event_handlers[MySm_EventId_PRESS] = ROOT_press;  // the next ancestor that handles this event is ROOT
}

static void ERROR_press(MySm* sm)
{
    // Setup handler for next ancestor that listens to `press` event.
    sm->ancestor_event_handler = ROOT_press;
    
    // ERROR behavior
    // uml: PRESS / { buzz(); }
    {
        // Step 1: execute action `buzz();`
        buzz();
        
        // Step 2: determine if ancestor gets to handle event next.
        sm->ancestor_event_handler = NULL;  // consume event
    } // end of behavior for ERROR
}


////////////////////////////////////////////////////////////////////////////////
// event handlers for state NORMAL
////////////////////////////////////////////////////////////////////////////////

static void NORMAL_enter(MySm* sm)
{
    // setup trigger/event handlers
    sm->current_state_exit_handler = NORMAL_exit;
    sm->current_event_handlers[MySm_EventId_DO] = NORMAL_do;
    
    // NORMAL behavior
    // uml: enter / { x = 0; }
    {
        // Step 1: execute action `x = 0;`
        sm->vars.x = 0;
    } // end of behavior for NORMAL
}

static void NORMAL_exit(MySm* sm)
{
    // adjust function pointers for this state's exit
    sm->current_state_exit_handler = ROOT_exit;
    sm->current_event_handlers[MySm_EventId_DO] = ROOT_do;  // the next ancestor that handles this event is ROOT
}

static void NORMAL_do(MySm* sm)
{
    // Setup handler for next ancestor that listens to `do` event.
    sm->ancestor_event_handler = ROOT_do;
    
    // NORMAL behavior
    // uml: do [err] TransitionTo(ERROR)
    if (err)
    {
        // Step 1: Exit states until we reach `ROOT` state (Least Common Ancestor for transition).
        exit_up_to_state_handler(sm, ROOT_exit);
        
        // Step 2: Transition action: ``.
        
        // Step 3: Enter/move towards transition target `ERROR`.
        ERROR_enter(sm);
        
        // Step 4: complete transition. Ends event dispatch. No other behaviors are checked.
        sm->state_id = MySm_StateId_ERROR;
        sm->ancestor_event_handler = NULL;
        return;
    } // end of behavior for NORMAL
}


////////////////////////////////////////////////////////////////////////////////
// event handlers for state RUNNING
////////////////////////////////////////////////////////////////////////////////

static void RUNNING_enter(MySm* sm)
{
    // setup trigger/event handlers
    sm->current_state_exit_handler = RUNNING_exit;
}

static void RUNNING_exit(MySm* sm)
{
    // adjust function pointers for this state's exit
    sm->current_state_exit_handler = NORMAL_exit;
}


////////////////////////////////////////////////////////////////////////////////
// event handlers for state PRE_HEAT
////////////////////////////////////////////////////////////////////////////////

static void PRE_HEAT_enter(MySm* sm)
{
    // setup trigger/event handlers
    sm->current_state_exit_handler = PRE_HEAT_exit;
    sm->current_event_handlers[MySm_EventId_DO] = PRE_HEAT_do;
    
    // PRE_HEAT behavior
    // uml: enter / { clear_timer(); }
    {
        // Step 1: execute action `clear_timer();`
        clear_timer();
    } // end of behavior for PRE_HEAT
}

static void PRE_HEAT_exit(MySm* sm)
{
    // adjust function pointers for this state's exit
    sm->current_state_exit_handler = RUNNING_exit;
    sm->current_event_handlers[MySm_EventId_DO] = NORMAL_do;  // the next ancestor that handles this event is NORMAL
}

static void PRE_HEAT_do(MySm* sm)
{
    // Setup handler for next ancestor that listens to `do` event.
    sm->ancestor_event_handler = NORMAL_do;
    
    // PRE_HEAT behavior
    // uml: do [after_ms(200)] TransitionTo(WARM_ENOUGH)
    if (after_ms(200))
    {
        // Step 1: Exit states until we reach `RUNNING` state (Least Common Ancestor for transition).
        PRE_HEAT_exit(sm);
        
        // Step 2: Transition action: ``.
        
        // Step 3: Enter/move towards transition target `WARM_ENOUGH`.
        WARM_ENOUGH_enter(sm);
        
        // Step 4: complete transition. Ends event dispatch. No other behaviors are checked.
        sm->state_id = MySm_StateId_WARM_ENOUGH;
        sm->ancestor_event_handler = NULL;
        return;
    } // end of behavior for PRE_HEAT
    
    // PRE_HEAT behavior
    // uml: do [too_cold] TransitionTo(PRE_HEAT)
    if (too_cold)
    {
        // Step 1: Exit states until we reach `RUNNING` state (Least Common Ancestor for transition).
        PRE_HEAT_exit(sm);
        
        // Step 2: Transition action: ``.
        
        // Step 3: Enter/move towards transition target `PRE_HEAT`.
        PRE_HEAT_enter(sm);
        
        // Step 4: complete transition. Ends event dispatch. No other behaviors are checked.
        sm->state_id = MySm_StateId_PRE_HEAT;
        sm->ancestor_event_handler = NULL;
        return;
    } // end of behavior for PRE_HEAT
}


////////////////////////////////////////////////////////////////////////////////
// event handlers for state WARM_ENOUGH
////////////////////////////////////////////////////////////////////////////////

static void WARM_ENOUGH_enter(MySm* sm)
{
    // setup trigger/event handlers
    sm->current_state_exit_handler = WARM_ENOUGH_exit;
    
    // WARM_ENOUGH behavior
    // uml: enter / { stuff(); }
    {
        // Step 1: execute action `stuff();`
        stuff();
    } // end of behavior for WARM_ENOUGH
}

static void WARM_ENOUGH_exit(MySm* sm)
{
    // adjust function pointers for this state's exit
    sm->current_state_exit_handler = RUNNING_exit;
}


////////////////////////////////////////////////////////////////////////////////
// event handlers for state STARTUP_BEEP
////////////////////////////////////////////////////////////////////////////////

static void STARTUP_BEEP_enter(MySm* sm)
{
    // setup trigger/event handlers
    sm->current_state_exit_handler = STARTUP_BEEP_exit;
    sm->current_event_handlers[MySm_EventId_DO] = STARTUP_BEEP_do;
    
    // STARTUP_BEEP behavior
    // uml: enter / { buzz(); clear_timer(); }
    {
        // Step 1: execute action `buzz(); clear_timer();`
        buzz(); clear_timer();
    } // end of behavior for STARTUP_BEEP
}

static void STARTUP_BEEP_exit(MySm* sm)
{
    // STARTUP_BEEP behavior
    // uml: exit / { stop_buzz(); }
    {
        // Step 1: execute action `stop_buzz();`
        stop_buzz();
    } // end of behavior for STARTUP_BEEP
    
    // adjust function pointers for this state's exit
    sm->current_state_exit_handler = NORMAL_exit;
    sm->current_event_handlers[MySm_EventId_DO] = NORMAL_do;  // the next ancestor that handles this event is NORMAL
}

static void STARTUP_BEEP_do(MySm* sm)
{
    // Setup handler for next ancestor that listens to `do` event.
    sm->ancestor_event_handler = NORMAL_do;
    
    // STARTUP_BEEP behavior
    // uml: do [after_ms(100) \n&& x >= 13] TransitionTo(RUNNING)
    if (after_ms(100) 
&& sm->vars.x >= 13)
    {
        // Step 1: Exit states until we reach `NORMAL` state (Least Common Ancestor for transition).
        STARTUP_BEEP_exit(sm);
        
        // Step 2: Transition action: ``.
        
        // Step 3: Enter/move towards transition target `RUNNING`.
        RUNNING_enter(sm);
        
        // RUNNING.<InitialState> behavior
        // uml: TransitionTo(PRE_HEAT)
        {
            // Step 1: Exit states until we reach `RUNNING` state (Least Common Ancestor for transition). Already at LCA, no exiting required.
            
            // Step 2: Transition action: ``.
            
            // Step 3: Enter/move towards transition target `PRE_HEAT`.
            PRE_HEAT_enter(sm);
            
            // Step 4: complete transition. Ends event dispatch. No other behaviors are checked.
            sm->state_id = MySm_StateId_PRE_HEAT;
            sm->ancestor_event_handler = NULL;
            return;
        } // end of behavior for RUNNING.<InitialState>
    } // end of behavior for STARTUP_BEEP
}

// Thread safe.
char const * MySm_state_id_to_string(MySm_StateId id)
{
    switch (id)
    {
        case MySm_StateId_ROOT: return "ROOT";
        case MySm_StateId_ERROR: return "ERROR";
        case MySm_StateId_NORMAL: return "NORMAL";
        case MySm_StateId_RUNNING: return "RUNNING";
        case MySm_StateId_PRE_HEAT: return "PRE_HEAT";
        case MySm_StateId_WARM_ENOUGH: return "WARM_ENOUGH";
        case MySm_StateId_STARTUP_BEEP: return "STARTUP_BEEP";
        default: return "?";
    }
}

// Thread safe.
char const * MySm_event_id_to_string(MySm_EventId id)
{
    switch (id)
    {
        case MySm_EventId_DO: return "DO";
        case MySm_EventId_PRESS: return "PRESS";
        default: return "?";
    }
}
