// Autogenerated with StateSmith
#pragma once
#include <stdint.h>

enum MySm_EventId
{
    MySm_EventId_EVENT = 0,
};

enum
{
    MySm_EventIdCount = 1
};

enum MySm_StateId
{
    MySm_StateId_ROOT = 0,
    MySm_StateId_GROUP = 1,
    MySm_StateId_STATE_1 = 2,
    MySm_StateId_STATE_2 = 3,
    MySm_StateId_STATE_3 = 4,
};

enum
{
    MySm_StateIdCount = 5
};

typedef struct MySm MySm;
typedef void (*MySm_Func)(MySm* sm);

struct MySm
{
    // Used internally by state machine. Feel free to inspect, but don't modify.
    enum MySm_StateId state_id;
    
    // Used internally by state machine. Don't modify.
    MySm_Func ancestor_event_handler;
    
    // Used internally by state machine. Don't modify.
    MySm_Func current_event_handlers[MySm_EventIdCount];
    
    // Used internally by state machine. Don't modify.
    MySm_Func current_state_exit_handler;
    
    // User variables. Can be used for inputs, outputs, user variables...
    struct
    {
        int cnt;
    } vars;
};

// State machine constructor. Must be called before start or dispatch event functions. Not thread safe.
void MySm_ctor(MySm* self);

// Starts the state machine. Must be called before dispatching events. Not thread safe.
void MySm_start(MySm* self);

// Dispatches an event to the state machine. Not thread safe.
void MySm_dispatch_event(MySm* self, enum MySm_EventId event_id);

// Converts a state id to a string. Thread safe.
const char* MySm_state_id_to_string(const enum MySm_StateId id);

