// Autogenerated with StateSmith 0.9.7-alpha.
// Algorithm: Balanced1. See https://github.com/StateSmith/StateSmith/wiki/Algorithms

#include "MySm.h"
#include "Leds.h"
#include <stdio.h>
#include <stdbool.h> // required for `consume_event` flag
#include <string.h> // for memset

// This function is used when StateSmith doesn't know what the active leaf state is at
// compile time due to sub states or when multiple states need to be exited.
static void exit_up_to_state_handler(MySm* sm, MySm_Func desired_state_exit_handler);

static void ROOT_enter(MySm* sm);

static void ROOT_exit(MySm* sm);

static void OFF_enter(MySm* sm);

static void OFF_exit(MySm* sm);

static void OFF_next(MySm* sm);

static void ON_enter(MySm* sm);

static void ON_exit(MySm* sm);

static void ON_reset(MySm* sm);

static void ON1_enter(MySm* sm);

static void ON1_exit(MySm* sm);

static void ON1_next(MySm* sm);

static void ON2_enter(MySm* sm);

static void ON2_exit(MySm* sm);

static void ON2_next(MySm* sm);

static void ON3_enter(MySm* sm);

static void ON3_exit(MySm* sm);

static void ON3_next(MySm* sm);


// State machine constructor. Must be called before start or dispatch event functions. Not thread safe.
void MySm_ctor(MySm* sm)
{
    memset(sm, 0, sizeof(*sm));
}

// Starts the state machine. Must be called before dispatching events. Not thread safe.
void MySm_start(MySm* sm)
{
    ROOT_enter(sm);
    // ROOT behavior
    // uml: TransitionTo(ROOT.<InitialState>)
    {
        // Step 1: Exit states until we reach `ROOT` state (Least Common Ancestor for transition). Already at LCA, no exiting required.
        
        // Step 2: Transition action: ``.
        
        // Step 3: Enter/move towards transition target `ROOT.<InitialState>`.
        // ROOT.<InitialState> is a pseudo state and cannot have an `enter` trigger.
        
        // ROOT.<InitialState> behavior
        // uml: TransitionTo(OFF)
        {
            // Step 1: Exit states until we reach `ROOT` state (Least Common Ancestor for transition). Already at LCA, no exiting required.
            
            // Step 2: Transition action: ``.
            
            // Step 3: Enter/move towards transition target `OFF`.
            OFF_enter(sm);
            
            // Step 4: complete transition. Ends event dispatch. No other behaviors are checked.
            sm->state_id = MySm_StateId_OFF;
            // No ancestor handles event. Can skip nulling `ancestor_event_handler`.
            return;
        } // end of behavior for ROOT.<InitialState>
    } // end of behavior for ROOT
}

// Dispatches an event to the state machine. Not thread safe.
void MySm_dispatch_event(MySm* sm, MySm_EventId event_id)
{
    MySm_Func behavior_func = sm->current_event_handlers[event_id];
    
    while (behavior_func != NULL)
    {
        sm->ancestor_event_handler = NULL;
        behavior_func(sm);
        behavior_func = sm->ancestor_event_handler;
    }
}

// This function is used when StateSmith doesn't know what the active leaf state is at
// compile time due to sub states or when multiple states need to be exited.
static void exit_up_to_state_handler(MySm* sm, MySm_Func desired_state_exit_handler)
{
    while (sm->current_state_exit_handler != desired_state_exit_handler)
    {
        sm->current_state_exit_handler(sm);
    }
}


////////////////////////////////////////////////////////////////////////////////
// event handlers for state ROOT
////////////////////////////////////////////////////////////////////////////////

static void ROOT_enter(MySm* sm)
{
    // setup trigger/event handlers
    sm->current_state_exit_handler = ROOT_exit;
}

static void ROOT_exit(MySm* sm)
{
    // State machine root is a special case. It cannot be exited. Mark as unused.
    (void)sm;
}


////////////////////////////////////////////////////////////////////////////////
// event handlers for state OFF
////////////////////////////////////////////////////////////////////////////////

static void OFF_enter(MySm* sm)
{
    // setup trigger/event handlers
    sm->current_state_exit_handler = OFF_exit;
    sm->current_event_handlers[MySm_EventId_NEXT] = OFF_next;
    
    // OFF behavior
    // uml: enter / { printf("--> Entered OFF.\n"); }
    {
        // Step 1: execute action `printf("--> Entered OFF.\n");`
        printf("--> Entered OFF.\n");
    } // end of behavior for OFF
    
    // OFF behavior
    // uml: enter / { Leds_set(0b000); }
    {
        // Step 1: execute action `Leds_set(0b000);`
        Leds_set(0b000);
    } // end of behavior for OFF
}

static void OFF_exit(MySm* sm)
{
    // OFF behavior
    // uml: exit / { printf("<-- Exited OFF.\n"); }
    {
        // Step 1: execute action `printf("<-- Exited OFF.\n");`
        printf("<-- Exited OFF.\n");
    } // end of behavior for OFF
    
    // adjust function pointers for this state's exit
    sm->current_state_exit_handler = ROOT_exit;
    sm->current_event_handlers[MySm_EventId_NEXT] = NULL;  // no ancestor listens to this event
}

static void OFF_next(MySm* sm)
{
    // No ancestor state handles `next` event.
    
    // OFF behavior
    // uml: NEXT TransitionTo(ON1)
    {
        // Step 1: Exit states until we reach `ROOT` state (Least Common Ancestor for transition).
        OFF_exit(sm);
        
        // Step 2: Transition action: ``.
        
        // Step 3: Enter/move towards transition target `ON1`.
        ON_enter(sm);
        ON1_enter(sm);
        
        // Step 4: complete transition. Ends event dispatch. No other behaviors are checked.
        sm->state_id = MySm_StateId_ON1;
        // No ancestor handles event. Can skip nulling `ancestor_event_handler`.
        return;
    } // end of behavior for OFF
}


////////////////////////////////////////////////////////////////////////////////
// event handlers for state ON
////////////////////////////////////////////////////////////////////////////////

static void ON_enter(MySm* sm)
{
    // setup trigger/event handlers
    sm->current_state_exit_handler = ON_exit;
    sm->current_event_handlers[MySm_EventId_RESET] = ON_reset;
    
    // ON behavior
    // uml: enter / { printf("--> Entered ON.\n"); }
    {
        // Step 1: execute action `printf("--> Entered ON.\n");`
        printf("--> Entered ON.\n");
    } // end of behavior for ON
}

static void ON_exit(MySm* sm)
{
    // ON behavior
    // uml: exit / { printf("<-- Exited ON.\n"); }
    {
        // Step 1: execute action `printf("<-- Exited ON.\n");`
        printf("<-- Exited ON.\n");
    } // end of behavior for ON
    
    // adjust function pointers for this state's exit
    sm->current_state_exit_handler = ROOT_exit;
    sm->current_event_handlers[MySm_EventId_RESET] = NULL;  // no ancestor listens to this event
}

static void ON_reset(MySm* sm)
{
    // No ancestor state handles `reset` event.
    
    // ON behavior
    // uml: RESET TransitionTo(OFF)
    {
        // Step 1: Exit states until we reach `ROOT` state (Least Common Ancestor for transition).
        exit_up_to_state_handler(sm, ROOT_exit);
        
        // Step 2: Transition action: ``.
        
        // Step 3: Enter/move towards transition target `OFF`.
        OFF_enter(sm);
        
        // Step 4: complete transition. Ends event dispatch. No other behaviors are checked.
        sm->state_id = MySm_StateId_OFF;
        // No ancestor handles event. Can skip nulling `ancestor_event_handler`.
        return;
    } // end of behavior for ON
}


////////////////////////////////////////////////////////////////////////////////
// event handlers for state ON1
////////////////////////////////////////////////////////////////////////////////

static void ON1_enter(MySm* sm)
{
    // setup trigger/event handlers
    sm->current_state_exit_handler = ON1_exit;
    sm->current_event_handlers[MySm_EventId_NEXT] = ON1_next;
    
    // ON1 behavior
    // uml: enter / { printf("--> Entered ON1.\n"); }
    {
        // Step 1: execute action `printf("--> Entered ON1.\n");`
        printf("--> Entered ON1.\n");
    } // end of behavior for ON1
    
    // ON1 behavior
    // uml: enter / { Leds_set(0b001); }
    {
        // Step 1: execute action `Leds_set(0b001);`
        Leds_set(0b001);
    } // end of behavior for ON1
}

static void ON1_exit(MySm* sm)
{
    // ON1 behavior
    // uml: exit / { printf("<-- Exited ON1.\n"); }
    {
        // Step 1: execute action `printf("<-- Exited ON1.\n");`
        printf("<-- Exited ON1.\n");
    } // end of behavior for ON1
    
    // adjust function pointers for this state's exit
    sm->current_state_exit_handler = ON_exit;
    sm->current_event_handlers[MySm_EventId_NEXT] = NULL;  // no ancestor listens to this event
}

static void ON1_next(MySm* sm)
{
    // No ancestor state handles `next` event.
    
    // ON1 behavior
    // uml: NEXT TransitionTo(ON2)
    {
        // Step 1: Exit states until we reach `ON` state (Least Common Ancestor for transition).
        ON1_exit(sm);
        
        // Step 2: Transition action: ``.
        
        // Step 3: Enter/move towards transition target `ON2`.
        ON2_enter(sm);
        
        // Step 4: complete transition. Ends event dispatch. No other behaviors are checked.
        sm->state_id = MySm_StateId_ON2;
        // No ancestor handles event. Can skip nulling `ancestor_event_handler`.
        return;
    } // end of behavior for ON1
}


////////////////////////////////////////////////////////////////////////////////
// event handlers for state ON2
////////////////////////////////////////////////////////////////////////////////

static void ON2_enter(MySm* sm)
{
    // setup trigger/event handlers
    sm->current_state_exit_handler = ON2_exit;
    sm->current_event_handlers[MySm_EventId_NEXT] = ON2_next;
    
    // ON2 behavior
    // uml: enter / { printf("--> Entered ON2.\n"); }
    {
        // Step 1: execute action `printf("--> Entered ON2.\n");`
        printf("--> Entered ON2.\n");
    } // end of behavior for ON2
    
    // ON2 behavior
    // uml: enter / { Leds_set(0b011); }
    {
        // Step 1: execute action `Leds_set(0b011);`
        Leds_set(0b011);
    } // end of behavior for ON2
}

static void ON2_exit(MySm* sm)
{
    // ON2 behavior
    // uml: exit / { printf("<-- Exited ON2.\n"); }
    {
        // Step 1: execute action `printf("<-- Exited ON2.\n");`
        printf("<-- Exited ON2.\n");
    } // end of behavior for ON2
    
    // adjust function pointers for this state's exit
    sm->current_state_exit_handler = ON_exit;
    sm->current_event_handlers[MySm_EventId_NEXT] = NULL;  // no ancestor listens to this event
}

static void ON2_next(MySm* sm)
{
    // No ancestor state handles `next` event.
    
    // ON2 behavior
    // uml: NEXT TransitionTo(ON3)
    {
        // Step 1: Exit states until we reach `ON` state (Least Common Ancestor for transition).
        ON2_exit(sm);
        
        // Step 2: Transition action: ``.
        
        // Step 3: Enter/move towards transition target `ON3`.
        ON3_enter(sm);
        
        // Step 4: complete transition. Ends event dispatch. No other behaviors are checked.
        sm->state_id = MySm_StateId_ON3;
        // No ancestor handles event. Can skip nulling `ancestor_event_handler`.
        return;
    } // end of behavior for ON2
}


////////////////////////////////////////////////////////////////////////////////
// event handlers for state ON3
////////////////////////////////////////////////////////////////////////////////

static void ON3_enter(MySm* sm)
{
    // setup trigger/event handlers
    sm->current_state_exit_handler = ON3_exit;
    sm->current_event_handlers[MySm_EventId_NEXT] = ON3_next;
    
    // ON3 behavior
    // uml: enter / { printf("--> Entered ON3.\n"); }
    {
        // Step 1: execute action `printf("--> Entered ON3.\n");`
        printf("--> Entered ON3.\n");
    } // end of behavior for ON3
    
    // ON3 behavior
    // uml: enter / { Leds_set(0b111); }
    {
        // Step 1: execute action `Leds_set(0b111);`
        Leds_set(0b111);
    } // end of behavior for ON3
}

static void ON3_exit(MySm* sm)
{
    // ON3 behavior
    // uml: exit / { printf("<-- Exited ON3.\n"); }
    {
        // Step 1: execute action `printf("<-- Exited ON3.\n");`
        printf("<-- Exited ON3.\n");
    } // end of behavior for ON3
    
    // adjust function pointers for this state's exit
    sm->current_state_exit_handler = ON_exit;
    sm->current_event_handlers[MySm_EventId_NEXT] = NULL;  // no ancestor listens to this event
}

static void ON3_next(MySm* sm)
{
    // No ancestor state handles `next` event.
    
    // ON3 behavior
    // uml: NEXT TransitionTo(ON1)
    {
        // Step 1: Exit states until we reach `ON` state (Least Common Ancestor for transition).
        ON3_exit(sm);
        
        // Step 2: Transition action: ``.
        
        // Step 3: Enter/move towards transition target `ON1`.
        ON1_enter(sm);
        
        // Step 4: complete transition. Ends event dispatch. No other behaviors are checked.
        sm->state_id = MySm_StateId_ON1;
        // No ancestor handles event. Can skip nulling `ancestor_event_handler`.
        return;
    } // end of behavior for ON3
}

// Thread safe.
char const * MySm_state_id_to_string(MySm_StateId id)
{
    switch (id)
    {
        case MySm_StateId_ROOT: return "ROOT";
        case MySm_StateId_OFF: return "OFF";
        case MySm_StateId_ON: return "ON";
        case MySm_StateId_ON1: return "ON1";
        case MySm_StateId_ON2: return "ON2";
        case MySm_StateId_ON3: return "ON3";
        default: return "?";
    }
}

// Thread safe.
char const * MySm_event_id_to_string(MySm_EventId id)
{
    switch (id)
    {
        case MySm_EventId_NEXT: return "NEXT";
        case MySm_EventId_RESET: return "RESET";
        default: return "?";
    }
}
