// Autogenerated with StateSmith
#include "MySm.h"
#include <stdbool.h> // required for `consume_event` flag
#include <string.h> // for memset

static void ROOT_enter(MySm* self);
static void ROOT_exit(MySm* self);

static void STATE_1_enter(MySm* self);
static void STATE_1_exit(MySm* self);
static void STATE_1_ev1(MySm* self);
static void STATE_1_ev2(MySm* self);

static void STATE_2_enter(MySm* self);
static void STATE_2_exit(MySm* self);

static void STATE_3_enter(MySm* self);
static void STATE_3_exit(MySm* self);

static void STATE_3__STATE_4_enter(MySm* self);
static void STATE_3__STATE_4_exit(MySm* self);

static void STATE_3__STATE_4__STATE_5_enter(MySm* self);
static void STATE_3__STATE_4__STATE_5_exit(MySm* self);

// This function is used when StateSmith doesn't know what the active leaf state is at compile time due to sub states
// or when multiple states need to be exited.
static void exit_up_to_state_handler(MySm* self, const MySm_Func desired_state_exit_handler);


void MySm_ctor(MySm* self)
{
    memset(self, 0, sizeof(*self));
}

static void exit_up_to_state_handler(MySm* self, const MySm_Func desired_state_exit_handler)
{
    while (self->current_state_exit_handler != desired_state_exit_handler)
    {
        self->current_state_exit_handler(self);
    }
}

void MySm_start(MySm* self)
{
    ROOT_enter(self);
    // ROOT behavior
    // uml: TransitionTo(ROOT.InitialState)
    {
        // Step 1: Exit states until we reach `ROOT` state (Least Common Ancestor for transition). Already at LCA, no exiting required.
        
        // Step 2: Transition action: ``.
        
        // Step 3: Enter/move towards transition target `ROOT.InitialState`.
        // ROOT.InitialState is a pseudo state and cannot have an `enter` trigger.
        
        // ROOT.InitialState behavior
        // uml: TransitionTo(STATE_1)
        {
            // Step 1: Exit states until we reach `ROOT` state (Least Common Ancestor for transition). Already at LCA, no exiting required.
            
            // Step 2: Transition action: ``.
            
            // Step 3: Enter/move towards transition target `STATE_1`.
            STATE_1_enter(self);
            
            // Step 4: complete transition. Ends event dispatch. No other behaviors are checked.
            self->state_id = MySm_StateId_STATE_1;
            // No ancestor handles event. Can skip nulling `self->ancestor_event_handler`.
            return;
        } // end of behavior for ROOT.InitialState
    } // end of behavior for ROOT
}

void MySm_dispatch_event(MySm* self, enum MySm_EventId event_id)
{
    MySm_Func behavior_func = self->current_event_handlers[event_id];
    
    while (behavior_func != NULL)
    {
        self->ancestor_event_handler = NULL;
        behavior_func(self);
        behavior_func = self->ancestor_event_handler;
    }
}

const char* MySm_state_id_to_string(const enum MySm_StateId id)
{
    switch (id)
    {
        case MySm_StateId_ROOT: return "ROOT";
        case MySm_StateId_STATE_1: return "STATE_1";
        case MySm_StateId_STATE_2: return "STATE_2";
        case MySm_StateId_STATE_3: return "STATE_3";
        case MySm_StateId_STATE_3__STATE_4: return "STATE_3__STATE_4";
        case MySm_StateId_STATE_3__STATE_4__STATE_5: return "STATE_3__STATE_4__STATE_5";
        default: return "?";
    }
}

////////////////////////////////////////////////////////////////////////////////
// event handlers for state ROOT
////////////////////////////////////////////////////////////////////////////////

static void ROOT_enter(MySm* self)
{
    // setup trigger/event handlers
    self->current_state_exit_handler = ROOT_exit;
}

static void ROOT_exit(MySm* self)
{
    // State machine root is a special case. It cannot be exited.
    (void)self;  // nothing to see here compiler. move along!
}


////////////////////////////////////////////////////////////////////////////////
// event handlers for state STATE_1
////////////////////////////////////////////////////////////////////////////////

static void STATE_1_enter(MySm* self)
{
    // setup trigger/event handlers
    self->current_state_exit_handler = STATE_1_exit;
    self->current_event_handlers[MySm_EventId_EV1] = STATE_1_ev1;
    self->current_event_handlers[MySm_EventId_EV2] = STATE_1_ev2;
}

static void STATE_1_exit(MySm* self)
{
    // adjust function pointers for this state's exit
    self->current_state_exit_handler = ROOT_exit;
    self->current_event_handlers[MySm_EventId_EV1] = NULL;  // no ancestor listens to this event
    self->current_event_handlers[MySm_EventId_EV2] = NULL;  // no ancestor listens to this event
}

static void STATE_1_ev1(MySm* self)
{
    // No ancestor state handles `ev1` event.
    
    // STATE_1 behavior
    // uml: EV1 TransitionTo(STATE_2)
    {
        // Step 1: Exit states until we reach `ROOT` state (Least Common Ancestor for transition).
        STATE_1_exit(self);
        
        // Step 2: Transition action: ``.
        
        // Step 3: Enter/move towards transition target `STATE_2`.
        STATE_2_enter(self);
        
        // Step 4: complete transition. Ends event dispatch. No other behaviors are checked.
        self->state_id = MySm_StateId_STATE_2;
        // No ancestor handles event. Can skip nulling `self->ancestor_event_handler`.
        return;
    } // end of behavior for STATE_1
}

static void STATE_1_ev2(MySm* self)
{
    // No ancestor state handles `ev2` event.
    
    // STATE_1 behavior
    // uml: EV2 TransitionTo(STATE_3__STATE_4__STATE_5)
    {
        // Step 1: Exit states until we reach `ROOT` state (Least Common Ancestor for transition).
        STATE_1_exit(self);
        
        // Step 2: Transition action: ``.
        
        // Step 3: Enter/move towards transition target `STATE_3__STATE_4__STATE_5`.
        STATE_3_enter(self);
        STATE_3__STATE_4_enter(self);
        STATE_3__STATE_4__STATE_5_enter(self);
        
        // Step 4: complete transition. Ends event dispatch. No other behaviors are checked.
        self->state_id = MySm_StateId_STATE_3__STATE_4__STATE_5;
        // No ancestor handles event. Can skip nulling `self->ancestor_event_handler`.
        return;
    } // end of behavior for STATE_1
}


////////////////////////////////////////////////////////////////////////////////
// event handlers for state STATE_2
////////////////////////////////////////////////////////////////////////////////

static void STATE_2_enter(MySm* self)
{
    // setup trigger/event handlers
    self->current_state_exit_handler = STATE_2_exit;
}

static void STATE_2_exit(MySm* self)
{
    // adjust function pointers for this state's exit
    self->current_state_exit_handler = ROOT_exit;
}


////////////////////////////////////////////////////////////////////////////////
// event handlers for state STATE_3
////////////////////////////////////////////////////////////////////////////////

static void STATE_3_enter(MySm* self)
{
    // setup trigger/event handlers
    self->current_state_exit_handler = STATE_3_exit;
}

static void STATE_3_exit(MySm* self)
{
    // adjust function pointers for this state's exit
    self->current_state_exit_handler = ROOT_exit;
}


////////////////////////////////////////////////////////////////////////////////
// event handlers for state STATE_3__STATE_4
////////////////////////////////////////////////////////////////////////////////

static void STATE_3__STATE_4_enter(MySm* self)
{
    // setup trigger/event handlers
    self->current_state_exit_handler = STATE_3__STATE_4_exit;
}

static void STATE_3__STATE_4_exit(MySm* self)
{
    // adjust function pointers for this state's exit
    self->current_state_exit_handler = STATE_3_exit;
}


////////////////////////////////////////////////////////////////////////////////
// event handlers for state STATE_3__STATE_4__STATE_5
////////////////////////////////////////////////////////////////////////////////

static void STATE_3__STATE_4__STATE_5_enter(MySm* self)
{
    // setup trigger/event handlers
    self->current_state_exit_handler = STATE_3__STATE_4__STATE_5_exit;
}

static void STATE_3__STATE_4__STATE_5_exit(MySm* self)
{
    // adjust function pointers for this state's exit
    self->current_state_exit_handler = STATE_3__STATE_4_exit;
}


